# Generated by Django 4.1 on 2022-09-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DollsDress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('available', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='media/img/')),
            ],
        ),
        migrations.CreateModel(
            name='InteriorDolls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('available', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='media/img/')),
            ],
        ),
        migrations.CreateModel(
            name='PlayDolls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('available', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='media/img/')),
            ],
        ),
        migrations.CreateModel(
            name='Toys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('available', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='media/img/')),
            ],
        ),
        migrations.CreateModel(
            name='ToysDress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('available', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='media/img/')),
            ],
        ),
        migrations.DeleteModel(
            name='Dolls',
        ),
    ]
